pipeline {
    agent any

    // triggers {
    //     pollSCM('H/1 * * * *')   // Every 1 min
    // }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/scaler-bhavya/jenkins-java.git'
            }
        }

        stage('Build') {
            steps {
                dir('Jenkins-demo-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('Jenkins-demo-app') {
                    sh 'java -jar target/*.jar'
                }
            }
        }
    }
}
